version: '3.8'
services:
  backend:
    image: microflask
    restart: always
    container_name: flaskweb
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  
  queue:
    image: microflask
    restart: always
    container_name: queue_flask
    command: 'python consumer.py'
    volumes:
      - .:/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: mysql:5.7.22
    restart: always
    container_name: flask_mysql
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    
    extra_hosts:
    - "host.docker.internal:host-gateway"