version: '3.8'
services:
  backend:
    image: microadmin
    restart: always
    container_name: web
    command: 'python manage.py runserver 0.0.0.0:8000 '
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  queue:
    image: microadmin
    restart: always
    container_name: queue_django
    command: 'python consumer.py'
    volumes:
      - .:/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: mysql:5.7.22
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"